name: Streamlit App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # or 3.9 / 3.11 depending on your machine

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lint check (optional but recommended)
      - name: Run flake8 lint
        run: |
          pip install flake8
          flake8 . --max-line-length=88 --ignore=E203,W503

      # 5. Test Streamlit app syntax (does not launch UI, just checks import works)
      - name: Validate Streamlit app
        run: |
          python -m py_compile app.py
          streamlit --version
